name: 'Filter based on comment'
description: 'Filters actions based on a comment content'
author: 'Jim Hester'
inputs:
  github-token:
    description: 'GitHub access token'
  filter-rexex:
    description: 'A regular expression to filter by'
    default: '.*'
runs:
  using: 'node12'
  main: 'lib/main.js'
